### ISSUE TITLE
Data type of HMM best hit scores

### ISSUE THREAD

**Issue by KGerhardt** [cruizperez/FastAAI#8]
In the kmer_extract function, selection of best HMM hits happens via parsing the filtered HMM file and selecting the highest score for each protein.

The problem is that the string.split() function returns a list of strings, not a best-matching type of each chunk. The HMM scores are being compared as strings, so "80" > "300" for the protein scores.

score = line[8]

in that function must be replaced by

score = float(line[8])

**Comment by cruizperez** [comment]
Corrected. Thanks Kenji!
